### ISSUE TITLE
unable to start virtual media

### ISSUE THREAD

**Issue by ssbarnea** [TheCase/IPMIView.app#1]
While I was able to start it on MacOS it seems tha Virtual Media button does not open the wizard so I cannot mount an ISO.

**Comment by TheCase** [comment]
I ran this without the wrapper and was able to repeat the same issue.  Its a problem with the IPMIView java app, not my wrapper.

I invite you to try this yourself:
```
$ cd /Applications/IPMIView.app/Resources/IPMIView
$ java -jar IPMIView20.jar
```

Following that, I recommend to reach out to BMC support regarding the issue:
https://www.supermicro.com/en/solutions/management-software/bmc-resources
