### ISSUE TITLE
Virtual Storage can't upload iso file

### ISSUE THREAD

**Issue by windowshome** [TheCase/IPMIView.app#11]
![image](https://user-images.githubusercontent.com/3413633/76651018-b8ed0280-659e-11ea-8ea3-3ae53ea93e89.png)

**Comment by TheCase** [comment]
Please verify that this issue is repeatable outside of this App wrapper:

```
cd ~/Applications/IPMIView.app/Contents/Resources/IPMIView
java -jar IPMIView20.jar
```

If it is, there is a bug with IPMIView, not this wrapper.

**Comment by windowshome** [comment]
Yes, or maybe it is bug

**Comment by erikpearson** [comment]
I ran into this issue too.  I was only able to get this to work with Oracle's version of Java 8 installed.  All versions of AdoptOpenJDK (8, 11, 14) didn't work.  Hope this helps.

**Comment by pgsengstock** [comment]
Tried the latest 8u251 from Oracle, and the latest AdoptOpenJDK, but neither work.  Definitely something with IPMIView, not the wrapper.

**Comment by erikpearson** [comment]
Agreed -- sorry, I spoke too soon earlier.  I was able to get IPMIView to come up using Oracle Java 8, but I still couldn't mount a Virtual Storage device (ISO) -- it would hang when trying to access the filesystem to select the ISO file.  I ended up installing it on VMWare Fusion running an open version of Windows 10.  Ugh.  You should be able to do the same with VirtualBox.

**Comment by TheCase** [comment]
based on @pgsengstock's reply, this sounds like a app/java problem - not a problem with the wrapper.  If you cannot repeat the problem running IPMIView without the wrapper, please feel free to open another issue.
