### ISSUE TITLE
Can't launch KVM Console, java not found

### ISSUE THREAD

**Issue by Phlogi** [TheCase/IPMIView.app#13]
When clicking on "Launch KVM Console":
![image](https://user-images.githubusercontent.com/6451003/82252320-1874df00-994f-11ea-9075-d81839a07e8f.png)

**Comment by Phlogi** [comment]
Inside the IPMIView.app i did the following as a workaround:

1. Remove everything inside the jre folder (there were linux java binaries)
2. Copied the Contents folder into the jre folder

**Comment by cloudnull** [comment]
> Inside the IPMIView.app i did the following as a workaround:
> 
> 1. Remove everything inside the jre folder (there were linux java binaries)
> 2. Copied the Contents folder into the jre folder

This worked perfectly

**Comment by jesse-troy** [comment]
@Phlogi or @cloudnull 

After following the setup instructions I have two directories:

~/Applications/IPMIView.app
and ~/IPMIView.app

I am not seeing a jre folder inside of either of them.

The IPMIView application launches and after connecting to a node It gives me the same message as above when trying to start the KVM Console.
