### ISSUE TITLE
iKVM64 not found?

### ISSUE THREAD

**Issue by spott** [TheCase/IPMIView.app#17]
When attempting to launch the KVM I get a `no iKVM64 in java.library.path: [.]`.

Not sure why it isn't being found, as there is a `libiKVM64.jnilib` in the directory, but I'm not familiar with Java library issues.

**Comment by spott** [comment]
There are a number of "solutions" to this around the internet, however, I can't figure out how they interact with this as they are frequently in other oses or using other tools (`javaws` for example):

* This one describes essentially moving back to x86 vs. x86-64.  No mention of macOS.  https://forums.servethehome.com/index.php?threads/psa-fix-supermicro-no-ikvm64-in-java-library-path.32302/
* This one modifies the `.jnlp` file (but there doesn't appear to be anything like that here... maybe something similar in the .lax files?): https://gist.github.com/eniac111/8292068
* This is another one that modifies the .jnlp files to download the correct libwin/liblinux/libmac files:  https://www.p14nd4.com/blog/2011/09/30/solved-no-ikvm64-in-java-library-path-on-supermicro-ip-kvm/. (note: to view the diff you might have to view source.)

Hopefully, this helps someone more knowledgable than me to figure this out.

**Comment by TheCase** [comment]
https://github.com/TheCase/IPMIView.app/wiki/Troubleshooting

**Comment by vleeuwenmenno** [comment]
> https://github.com/TheCase/IPMIView.app/wiki/Troubleshooting
```
❯ java -jar IPMIView20.jar
com.supermicro.ipmi.IPMIException: Invalid data field in Request(CCh)
	at com.supermicro.ipmi.IPMICommand.ccode2Exception(IPMICommand.java:35)
	at com.supermicro.ipmi.IPMIOEMPortServiceCommand.getPort(IPMIOEMPortServiceCommand.java:50)
	at IPMIView20.KVMATENPanel.lambda$jButton1_actionPerformed$13(KVMATENPanel.java:477)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
![image](https://user-images.githubusercontent.com/46482143/197371715-10e9d338-7a6c-4ae2-958f-48291e812e80.png)

This is what I get on my macOS M1 install. Can't get to see my KVM console in any way 💢 Any ideas?

**Comment by TheCase** [comment]
From  https://github.com/TheCase/IPMIView.app/wiki/Troubleshooting

```If you have issues with IMPIView using this method, please contact SuperMicro support. This means the problem is related to the java application and/or your computer setup, not this wrapper.```

While I would love to help out, I cannot reproduce the issue.
