### ISSUE TITLE
Cannot launch KVM Console

### ISSUE THREAD

**Issue by barad1tos** [TheCase/IPMIView.app#2]
The app is running good but in way of starting to launch KVM Console, there is an error:

`Cannot run program "./jre/Contents/Home/bin/java": error=2, No such file or directory`

![Скриншот 2019-08-14 14 06 58](https://user-images.githubusercontent.com/18615195/63016621-d341ef00-be9c-11e9-961a-4207d1aa525d.png)

**Comment by loozhengyuan** [comment]
@barad1tos Just encountered this problem as well. Did you manage to find a fix for this?

**Comment by TheCase** [comment]
I would inspect your jre/bin directory under your application folder:

`ls -la /Applications/IPMIView.app/Resources/IPMIView/jre/bin`

**Comment by loozhengyuan** [comment]
@TheCase Thanks for replying! The `jre/bin` directory is indeed present. Since it does not seem possible to change the directory (I think?), I've also tried creating symbolic links such that `ls -la /Applications/IPMIView.app/Resources/IPMIView/jre/bin` or `ls -la /Applications/IPMIView.app/Resources/IPMIView/jre/Contents/Home/bin` directories are present but this still doesn't work.

```sh
$ ls -la /Applications/IPMIView.app/Resources/IPMIView/jre/Contents/Home/bin/
total 696
drwxr-xr-x@ 13 user  admin     416 Nov 23 17:51 .
drwxr-xr-x@  8 user  admin     256 Nov 23 18:26 ..
-rwxr-xr-x@  1 user  admin    8702 Nov 23 17:51 java
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 jjs
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 keytool
-rwxr-xr-x@  1 user  admin    8885 Nov 23 17:51 orbd
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 pack200
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 policytool
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 rmid
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 rmiregistry
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 servertool
-rwxr-xr-x@  1 user  admin    8885 Nov 23 17:51 tnameserv
-rwxr-xr-x@  1 user  admin  233286 Nov 23 17:51 unpack200
```
```sh
$ ls -la /Applications/IPMIView.app/Resources/IPMIView/jre/bin/              
total 696
drwxr-xr-x@ 13 user  admin     416 Nov 23 17:51 .
drwxr-xr-x@  8 user  admin     256 Nov 23 18:26 ..
-rwxr-xr-x@  1 user  admin    8702 Nov 23 17:51 java
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 jjs
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 keytool
-rwxr-xr-x@  1 user  admin    8885 Nov 23 17:51 orbd
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 pack200
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 policytool
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 rmid
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 rmiregistry
-rwxr-xr-x@  1 user  admin    8821 Nov 23 17:51 servertool
-rwxr-xr-x@  1 user  admin    8885 Nov 23 17:51 tnameserv
-rwxr-xr-x@  1 user  admin  233286 Nov 23 17:51 unpack200
```

**Comment by TheCase** [comment]
https://github.com/TheCase/IPMIView.app/wiki/Troubleshooting

**Comment by TheCase** [comment]
https://github.com/TheCase/IPMIView.app/issues/5#issuecomment-570100185
