### ISSUE TITLE
KVM console "Connection failed"

### ISSUE THREAD

**Issue by a-pichard** [TheCase/IPMIView.app#24]
Hello
I am trying to access the remote console using KVM but i'm having this issue
<img width="330" alt="Screenshot 2023-03-15 at 14 07 49" src="https://user-images.githubusercontent.com/47189953/225318067-54d9c78f-5c6e-4767-b251-4be4e545da21.png">

It happens after clicking on "Launch KVM console"

Does anyone have an idea ?

**Comment by TheCase** [comment]
I would ask you to run the app without the wrapper and see if you have the same issue.  

https://github.com/TheCase/IPMIView.app/wiki/Troubleshooting

**Comment by shabarin** [comment]
Hi @TheCase ! 
I have the same issue.
I did:
```
cd ~/Applications/IPMIView.app/Contents/Resources/IPMIView/     #NOTE: see the 'Contents' folder in between, it's not the same path as in the wiki
java -jar IPMIView20.jar
```
The error message persists. Probably this is not an issue with the wrapper, but just in case you have an idea of how to solve this anyway.
