### ISSUE TITLE
Newer version available

### ISSUE THREAD

**Issue by gothickitty93** [TheCase/IPMIView.app#28]
There is a newer version available, version 2.21.1, located here https://www.supermicro.com/Bios/sw_download/588/IPMIView_2.21.1_build.230720_bundleJRE_Linux_x64.tar.gz

**Comment by ChrisCarini** [comment]
Hi @gothickitty93 - thanks for opening this issue.

It's a bummer they don't allow directory listing on  https://www.supermicro.com/Bios/sw_download/588/ - that makes making a change here more complicated.

Do you feel comfortable submitting a PR with the necessary changes?

**Comment by gothickitty93** [comment]
As much as I hate to admit it, I can’t code. However, it does appear to me like the url would have to be hardcoded into the script, and then updated with every new release…? (I just started learning how git ACTUALLY works today for work…lul)

**Comment by ChrisCarini** [comment]
> As much as I hate to admit it, I can’t code.

Just remember, there was a time in everyones' lives where they couldn't code, too. 😉 

> However, it does appear to me like the url would have to be hardcoded into the script, and then updated with every new release…?

Yes, it seems like that would need to happen.


If you'd like to have a try at making the change, and are open to feedback/collaboration on the PR, please feel free to give it a try! :)

**Comment by gothickitty93** [comment]
I have created a fork, and will start work on it as soon as I have some time

**Comment by ChrisCarini** [comment]
> I have created a fork, and will start work on it as soon as I have some time

Sounds good - keep this issue updated with any progress! 🙏 🙇

**Comment by TheCase** [comment]
Hey guys - sorry for the radio silence over here.  Life and such... you know.

I believe I have found a way to programmatically determine the latest version.  PR incoming.

**Comment by ChrisCarini** [comment]
> Hey guys - sorry for the radio silence over here. Life and such... you know.
> 
> I believe I have found a way to programmatically determine the latest version. PR incoming.

Nice!! Feel free to tag me for a review / sanity-check! :)

**Comment by TheCase** [comment]
#29

**Comment by gothickitty93** [comment]
I will test it out tomorrow at work, and let you know how it goes.

**Comment by gothickitty93** [comment]
I can confirm the PR works as expected.

**Comment by thisiskeithb** [comment]
> I can confirm the PR works as expected.

Have you tried the (Java) KVM Console?

Everything appears to work, except I get a "The function can't support on mac" message when launching the (Java) KVM Console with `IPMIView_2.21.1_build.230720_bundleJRE_Linux_x64.tar.gz` downloaded with the updated `script.sh` from #29 / [parse_latest](https://github.com/TheCase/IPMIView.app/tree/parse_latest) branch:

<img width="452" alt="image" src="https://github.com/user-attachments/assets/96de64d2-10eb-403c-856c-5d661ddeb6d4">

macOS Sonoma 14.7 on an Intel Mac.

Edit: The KVM Console works fine using the same IPMIView version & build on Windows 10.

**Comment by gothickitty93** [comment]
I had a similar issue on macOS Sonoma 14.7 on an Intel Mac with 2.21.1. I upgraded to macOS 15, and it's working fine. I'm connecting to a system with a X10 board. My Java is GraalVM 17 Enterprise

**Comment by TheCase** [comment]
@gothickitty93 @thisiskeithb would it be possible to open a new Issue regarding your console problem?  I believe the original issue, regarding the latest version update, has been addressed in PR #29 (still awaiting review)

**Comment by gothickitty93** [comment]
Sounds good. I'm gonna mark this as resolved. I've opened issue #30
