### ISSUE TITLE
New download address

### ISSUE THREAD

**Issue by tnewton1** [TheCase/IPMIView.app#3]
Supermicro has placed a password on their FTP site. You must now download IPMI from https://www.supermicro.com/SwDownload/SwSelect_Free.aspx?cat=IPMI

**Comment by SirMaple** [comment]
IPMI can also be found here -> https://ftp.supermicro.com/wftp/utility/IPMIView/Linux/

Parent directories are also accessible.

**Comment by TheCase** [comment]
Thanks for the info! I updated the readme with the http URL
