### ISSUE TITLE
Launch KVM Console failed

### ISSUE THREAD

**Issue by windowshome** [TheCase/IPMIView.app#5]
![image](https://user-images.githubusercontent.com/3413633/69966790-16aa9100-1552-11ea-9b66-985d3087488c.png)

**Comment by TheCase** [comment]
https://github.com/TheCase/IPMIView.app/wiki/Troubleshooting

**Comment by ScuttleSE** [comment]
Should make a note that this _DOES NOT WORK_ in Catalina, it spits out the exact same error as above.

**Comment by TheCase** [comment]
Have you tested loading the jar from the command line?

```
$ pwd
/Applications/IPMIView.app
$ java -jar Resources/IPMIView/IPMIView20.jar
```

**Comment by windowshome** [comment]
![image](https://user-images.githubusercontent.com/3413633/71613418-590ece80-2be1-11ea-8e40-3bf971c3dc16.png)

**Comment by ScuttleSE** [comment]
Same result as when I'm double-clicking the application

**Comment by TheCase** [comment]
Please pull down the latest commit.  I added some fixes that relink to Mac's java and notes about how to deal with security and privacy system changes to run the console.  Please let me know how it works out for you.

**Comment by loozhengyuan** [comment]
@TheCase Reporting back on the latest commits on the `master` branch. I'm encountering a problem where I am unable to add the `java` app to the `Security & Privacy > Input Monitoring` section. Here's a screenshot:
<img width="668" alt="Screenshot 2020-01-02 at 3 25 54 PM" src="https://user-images.githubusercontent.com/3350651/71655927-2d701d80-2d74-11ea-93af-cf8fb50f26ed.png">

With reference to the screenshot, you would see that there is no +/- option as it would for the other sections where there is at least 1 other app listed.

Can't find much info online except [this other occurrence](https://discussions.apple.com/thread/250723031) on Apple Community. Did you encounter this issue as well?

**Comment by TheCase** [comment]
Have you tried running the console yet?  Java actually showed up in that list on its own in several of my tests - I believe it adds itself when it is discovered that it needs permission to run properly.

**Comment by loozhengyuan** [comment]
I hope i understood what you meant when I ran the following commands:

```sh
cd ~/Applications/IPMIView.app/Resources/IPMIView/
java -jar IPMIView20.jar
java -jar iKVM.jar
```

Running `iKVM.jar` alone, after accepting all the security prompts, leads to this error message:

<img width="386" alt="Screenshot 2020-01-03 at 9 08 11 AM" src="https://user-images.githubusercontent.com/3350651/71702472-9efaab00-2e0a-11ea-9cdc-34b25f29127b.png">

It still does not work though, i.e. the `java` app does not shop up on the `Input Monitoring` page. I've also tried restarting as well, but it doesn't show up.

I guess the alternative here would be for me to try download another app that does request for the same privacy permissions. I'll report back again when I manage to get pass this, thank you!

**Comment by windowshome** [comment]
I already pull again ，but problem is not resolve;
![Uploading image.png…]()

**Comment by windowshome** [comment]
I already pull again ，but problem is not resolve;

**Comment by windowshome** [comment]
I already pull again ，but problem is not resolve;
![image](https://user-images.githubusercontent.com/3413633/71759684-667ece00-2eeb-11ea-9e42-6656404d0ce1.png)

**Comment by TheCase** [comment]
@windowshome did you run the included shell script?

**Comment by TheCase** [comment]
@loozhengyuan I opened a new issue for the Privacy problem you're having see #8

**Comment by loozhengyuan** [comment]
@TheCase Couldn't get it to run on my laptop, but happy to report that the newest changes works perfectly on a fresh Catalina instance.

![Screenshot 2020-01-05 at 11 35 49 AM](https://user-images.githubusercontent.com/3350651/71774797-f71ee200-2faf-11ea-9d79-d1f96d367813.png)

```sh
$ java --version
java 13 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57
```

**Comment by TheCase** [comment]
@windowshome did you run the included shell script?

**Comment by deoxykev** [comment]
Hi all, I had this problem as well on Catalina. I solved it using:
```
cd </path/to/IPMIView_2.16.0_build.190815_bundleJRE_Linux_x64>
mkdir -p jre/Contents/Home/bin/
cd jre/Contents/Home/bin/
ln -s $(which java) java
```

This links the installed java binary to the file that IPMIView is looking for.

Thanks @TheCase for working on the instructions for this! Appreciate it.

**Comment by TheCase** [comment]
shell script includes improvements - Closing.
