### ISSUE TITLE
problem adding Input Monitoring Privacy permission

### ISSUE THREAD

**Issue by TheCase** [TheCase/IPMIView.app#8]
@TheCase Reporting back on the latest commits on the `master` branch. I'm encountering a problem where I am unable to add the `java` app to the `Security & Privacy > Input Monitoring` section. Here's a screenshot:
<img width="668" alt="Screenshot 2020-01-02 at 3 25 54 PM" src="https://user-images.githubusercontent.com/3350651/71655927-2d701d80-2d74-11ea-93af-cf8fb50f26ed.png">

With reference to the screenshot, you would see that there is no +/- option as it would for the other sections where there is at least 1 other app listed.

Can't find much info online except [this other occurrence](https://discussions.apple.com/thread/250723031) on Apple Community. Did you encounter this issue as well?

_Originally posted by @loozhengyuan in https://github.com/TheCase/IPMIView.app/issues/5#issuecomment-570134896_

**Comment by TheCase** [comment]
opening as a new issue

**Comment by TheCase** [comment]
I ran the install on a new user account on Catalina.  This my Preference Pane prior to running IMPIView:

<img width="780" alt="Screen Shot 2020-01-04 at 12 06 45 PM" src="https://user-images.githubusercontent.com/924011/71770520-b4df9d00-2eea-11ea-83dc-ab1cc44905f6.png">

I am immediately presented with the dialog when I click on `Launch KVM Console`:

<img width="671" alt="Screen Shot 2020-01-04 at 12 01 35 PM" src="https://user-images.githubusercontent.com/924011/71770496-46024400-2eea-11ea-87e6-48c8e6a62902.png">

Clicking `Open System Preferences` brings me to the Preference Panel for it:

<img width="780" alt="Screen Shot 2020-01-04 at 12 01 39 PM" src="https://user-images.githubusercontent.com/924011/71770511-8d88d000-2eea-11ea-87cc-8adb03d6de8a.png">

My only suggestion at this point would be to work with Apple support to figure out why java is not triggering a dialog.

**Comment by TheCase** [comment]
In repeating this several times, I have noticed there are occasions where the window does not present itself to focus and appears to be lost.  Use AppExpose (F3 function key or 4 finger swipe up) to locate the possibly "lost" dialog.

**Comment by loozhengyuan** [comment]
As reported in https://github.com/TheCase/IPMIView.app/issues/5#issuecomment-570849275, I am unable to replicate this issue on a new Catalina instance so I think the issue is probably with some configuration I made on my end. The script should have no problems running normal circumstances.
